apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - image: thanawit09/react-app:0.1
        imagePullPolicy: Always
        name: react-app
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "64Mi"
            memory: "250m"
          requests:
            cpu: "128Mi"
            memory: "500m"

