apiVersion: v1
kind: Service
metadata:
  name: react-app
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31000
  selector:
    app: react-app